defaults: &defaults
  adapter: postgresql
  username: postgres
  password: psql
  encoding: utf8
  host: localhost

development:
  database: dchq_development
  <<: *defaults

production:
  database: dchq_production
  <<: *defaults

